name: Workflow for Codecov Action
on: [push, pull_request]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install codecov
        pip install -r requirements.txt
    - name: Build and publish
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        python3 socks5_server.py&
        coverage run test.py
        codecov --token=$CODECOV_TOKEN
